#!/bin/bash

## sshd back
cp /etc/ssh/sshd_config /etc/ssh/sshd_back_$RANDOM > /dev/null 2>&1

## Acceso Rapido
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1

## Version
rm -rf $HOME/versao* > /dev/null 2>&1 
wget $HOME/versao https://raw.githubusercontent.com/venturesolution/VSAIOMANAGER/master/versao > /dev/null 2>&1
apt-get update -y; apt-get full-upgrade -y; wget https://raw.githubusercontent.com/venturesolution/VSAIOMANAGER/master/Plus; chmod +x Plus* && ./Plus
## Systemverify
rm -rf $HOME/systemverify* > /dev/null 2>&1
